name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: sthwalonyoni
          POSTGRES_PASSWORD: Exec10Luxury
          POSTGRES_DB: execuhire_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo, pdo_pgsql
          
      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Set up test database
        run: bash scripts/setup-test-db.sh
        env:
          DB_USER: sthwalonyoni
          DB_PASS: Exec10Luxury
          DB_NAME: execuhire_test

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
        env:
          DB_HOST: localhost
          DB_USER: sthwalonyoni
          DB_PASS: Exec10Luxury
          DB_NAME: execuhire_test
